import computerGaming1 from '../../assets/computerGaming1.jpg'
import computerGaming2 from '../../assets/computerGaming2.jpg'
import computerGaming3 from '../../assets/computerGaming3.jpg'
import computerGaming4 from '../../assets/computerGaming4.jpg'
import computerGaming5 from '../../assets/computerGaming5.jpg'
import computerGaming6 from '../../assets/computerGaming6.jpg'
import computerGaming7 from '../../assets/computerGaming7.jpg'
import computerGaming8 from '../../assets/computerGaming8.jpg'
import consoleGaming1 from '../../assets/Console1.jpg'
import consoleGaming2 from '../../assets/Console2.jpg'
import consoleGaming3 from '../../assets/Console3.jpg'
import consoleGaming4 from '../../assets/Console4.jpg'
import consoleGaming5 from '../../assets/Console5.jpg'
import consoleGaming6 from '../../assets/Console6.jpg'
import consoleGaming7 from '../../assets/Console7.jpg'
import consoleGaming8 from '../../assets/Console8.jpg'
import mouseGaming1 from '../../assets/Mouse1.webp'
import mouseGaming2 from '../../assets/Mouse2.jpg'
import mouseGaming3 from '../../assets/Mouse3.jpg'
import mouseGaming4 from '../../assets/Mouse4.png'
import mouseGaming5 from '../../assets/Mouse5.jfif'
import mouseGaming6 from '../../assets/Mouse6.webp'
import mouseGaming7 from '../../assets/Mouse7.webp'
import mouseGaming8 from '../../assets/Mouse8.jfif'
import keyboardGaming1 from '../../assets/Keyboard1.jpeg'
import keyboardGaming2 from '../../assets/Keyboard2.webp'
import keyboardGaming3 from '../../assets/Keyboard3.png'
import keyboardGaming4 from '../../assets/Keyboard4.jpg'
import keyboardGaming5 from '../../assets/Keyboard5.jpg'
import keyboardGaming6 from '../../assets/Keyboard6.webp'
import keyboardGaming7 from '../../assets/Keyboard7.webp'
import keyboardGaming8 from '../../assets/Keyboard8.webp'
import headphoneGaming1 from '../../assets/headphone1.webp'
import headphoneGaming2 from '../../assets/headphone2.webp'
import headphoneGaming3 from '../../assets/headphone3.webp'
import headphoneGaming4 from '../../assets/headphone4.jpg'
import headphoneGaming5 from '../../assets/headphone5.png'
import headphoneGaming6 from '../../assets/headphone6.jfif'
import headphoneGaming7 from '../../assets/headphone7.jfif'
import headphoneGaming8 from '../../assets/headphone8.jfif'
import MinitorsGaming1 from '../../assets/Monitor1.jpg'
import MinitorsGaming2 from '../../assets/Monitor2.jfif'
import MinitorsGaming3 from '../../assets/Monitor3.webp'
import MinitorsGaming4 from '../../assets/Monitor4.jfif'
import MinitorsGaming5 from '../../assets/Monitor5.jfif'
import MinitorsGaming6 from '../../assets/Monitor6.jfif'
import MinitorsGaming7 from '../../assets/Monitor7.jfif'
import MinitorsGaming8 from '../../assets/Monitor8.jpg'

export const computerGaming = [
  {
    id: 1,
    category: 'Gaming PC',
    name: 'Predator Helios 300',
    rating: '4.8',
    reveiw: '(123 reviews)',
    price: '1499$',
    image: computerGaming1,
    description: 'A high-performance gaming laptop built for speed and precision. Perfect for gamers who demand smooth FPS and stunning visuals.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd0ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd0ff]',
    stockShadow: 'shadow-[0_0_10px_#f78eff]',
    bgBtn: 'bg-fuchsia-500',
    borderColor: 'border-fuchsia-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ff48ff,0_0_20px_#ff48ff,0_0_40px_#ff48ff]',
    textColor: 'text-fuchsia-500',
    hoverText: 'group-hover:text-fuchsia-500',
  },
  {
    id: 2,
    category: 'Gaming PC',
    name: 'MSI Raider GE76',
    rating: '4.6',
    reveiw: '(98 reviews)',
    price: '2299$',
    image: computerGaming2,
    description: 'Engineered for elite gamers with powerful RTX graphics. Delivers lightning-fast refresh rates and immersive gameplay.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffff]',
    stockShadow: 'shadow-[0_0_10px_#aaffff]',
    bgBtn: 'bg-teal-500',
    borderColor: 'border-teal-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffff,0_0_20px_#aaffff,0_0_40px_#aaffff]',
    textColor: 'text-teal-500',
    hoverText: 'group-hover:text-teal-500',
  },
  {
    id: 3,
    category: 'Gaming PC',
    name: 'ASUS ROG Strix G15',
    rating: '4.7',
    reveiw: '(210 reviews)',
    price: '1799$',
    image: computerGaming3,
    description: 'ROG power with stunning RGB aesthetics and precision cooling. Built to handle intense gaming marathons with ease.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffdfa3]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffdfa3]',
    stockShadow: 'shadow-[0_0_10px_#f78eff]',
    bgBtn: 'bg-orange-500',
    borderColor: 'border-orange-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffdfa3,0_0_20px_#ffdfa3,0_0_40px_#ffdfa3]',
    textColor: 'text-orange-500',
    hoverText: 'group-hover:text-orange-500',
  },
  {
    id: 4,
    category: 'Gaming PC',
    name: 'Alienware x17 R2',
    rating: '4.9',
    reveiw: '(145 reviews)',
    price: '3499$',
    image: computerGaming4,
    description: 'Ultra-premium design with unmatched performance and display quality. Ideal for pro gamers and creators alike.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffa1a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffa1a1]',
    stockShadow: 'shadow-[0_0_10px_#ffa1a1]',
    bgBtn: 'bg-red-500',
    borderColor: 'border-red-500',
    textShadow:'group-hover:[text-shadow:0_0_10px_#ffa1a1,0_0_20px_#ffa1a1,0_0_40px_#ffa1a1]',
    textColor: 'text-red-500',
    hoverText: 'group-hover:text-red-500',
  },
  {
    id: 5,
    category: 'Gaming PC',
    name: 'Razer Blade 15',
    rating: '4.7',
    reveiw: '(134 reviews)',
    price: '1999$',
    image: computerGaming5,
    description: 'Sleek, portable, and powerful — a perfect balance for gaming and productivity. Features a crisp QHD display and solid build.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffaa]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffaa]',
    stockShadow: 'shadow-[0_0_10px_#aaffaa]',
    bgBtn: 'bg-green-500',
    borderColor: 'border-green-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffaa,0_0_20px_#aaffaa,0_0_40px_#aaffaa]',
    textColor: 'text-green-500',
    hoverText: 'group-hover:text-green-500',
  },
  {
    id: 6,
    category: 'Gaming PC',
    name: 'HP Omen 17',
    rating: '4.5',
    reveiw: '(89 reviews)',
    price: '1699$',
    image: computerGaming6,
    description: 'Built for power and endurance, the Omen 17 combines high-end specs with sleek design. Great for gaming or creative work.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaccff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaccff]',
    stockShadow: 'shadow-[0_0_10px_#aaccff]',
    bgBtn: 'bg-blue-500',
    borderColor: 'border-blue-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaccff,0_0_20px_#aaccff,0_0_40px_#aaccff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 7,
    category: 'Gaming PC',
    name: 'Lenovo Legion 7',
    rating: '4.6',
    reveiw: '(102 reviews)',
    price: '1899$',
    image: computerGaming7,
    description: 'Smooth performance meets premium design. Legion 7 delivers stunning visuals and superior thermal control.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffbfff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffbfff]',
    stockShadow: 'shadow-[0_0_10px_#ffbfff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffbfff,0_0_20px_#ffbfff,0_0_40px_#ffbfff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 8,
    category: 'Gaming PC',
    name: 'Gigabyte Aorus 15G',
    rating: '4.4',
    reveiw: '(76 reviews)',
    price: '1599$',
    image: computerGaming8,
    description: 'A lightweight powerhouse designed for serious gamers. Fast refresh rates and mechanical keys elevate your play.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd8a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd8a1]',
    stockShadow: 'shadow-[0_0_10px_#ffd8a1]',
    bgBtn: 'bg-yellow-500',
    borderColor: 'border-yellow-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffd8a1,0_0_20px_#ffd8a1,0_0_40px_#ffd8a1]',
    textColor: 'text-yellow-500',
    hoverText: 'group-hover:text-yellow-500',
  },
];

export const consoleGaming = [
  {
    id: 9,
    category: 'Console',
    name: 'PlayStation 5',
    rating: '4.9',
    reveiw: '(230 reviews)',
    price: '499$',
    image: consoleGaming1,
    description: 'Experience next-gen performance with blazing-fast load times. Stunning 4K visuals and adaptive triggers redefine gameplay.',
    shadow: 'hover:shadow-[0_0_10px_5px_#9ab0ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#9ab0ff]',
    stockShadow: 'shadow-[0_0_10px_#9ab0ff]',
    bgBtn: 'bg-blue-600',
    borderColor: 'border-blue-600',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#9ab0ff,0_0_20px_#9ab0ff,0_0_40px_#9ab0ff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 10,
    category: 'Console',
    name: 'Xbox Series X',
    rating: '4.8',
    reveiw: '(187 reviews)',
    price: '499$',
    image: consoleGaming2,
    description: 'The most powerful Xbox ever made for ultra-smooth 4K gaming. Lightning-fast load speeds and true next-gen immersion.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffaa]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffaa]',
    stockShadow: 'shadow-[0_0_10px_#aaffaa]',
    bgBtn: 'bg-green-600',
    borderColor: 'border-green-600',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffaa,0_0_20px_#aaffaa,0_0_40px_#aaffaa]',
    textColor: 'text-green-500',
    hoverText: 'group-hover:text-green-500',
  },
  {
    id: 11,
    category: 'Console',
    name: 'Nintendo Switch OLED',
    rating: '4.7',
    reveiw: '(210 reviews)',
    price: '349$',
    image: consoleGaming3,
    description: 'Enjoy vibrant OLED visuals in handheld or docked mode. Perfect for on-the-go and family-friendly gaming sessions.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffdfa3]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffdfa3]',
    stockShadow: 'shadow-[0_0_10px_#ffdfa3]',
    bgBtn: 'bg-orange-500',
    borderColor: 'border-orange-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffdfa3,0_0_20px_#ffdfa3,0_0_40px_#ffdfa3]',
    textColor: 'text-orange-500',
    hoverText: 'group-hover:text-orange-500',
  },
  {
    id: 12,
    category: 'Console',
    name: 'PlayStation 4 Pro',
    rating: '4.6',
    reveiw: '(300 reviews)',
    price: '399$',
    image: consoleGaming4,
    description: 'Classic gaming power with enhanced 4K support. A reliable favorite with a vast library of iconic titles.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffa1a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffa1a1]',
    stockShadow: 'shadow-[0_0_10px_#ffa1a1]',
    bgBtn: 'bg-red-500',
    borderColor: 'border-red-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffa1a1,0_0_20px_#ffa1a1,0_0_40px_#ffa1a1]',
    textColor: 'text-red-500',
    hoverText: 'group-hover:text-red-500',
  },
  {
    id: 13,
    category: 'Console',
    name: 'Xbox Series S',
    rating: '4.5',
    reveiw: '(140 reviews)',
    price: '299$',
    image: consoleGaming5,
    description: 'Compact yet powerful digital console for smooth gameplay. Affordable next-gen experience in a sleek design.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffff]',
    stockShadow: 'shadow-[0_0_10px_#aaffff]',
    bgBtn: 'bg-teal-500',
    borderColor: 'border-teal-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffff,0_0_20px_#aaffff,0_0_40px_#aaffff]',
    textColor: 'text-teal-500',
    hoverText: 'group-hover:text-teal-500',
  },
  {
    id: 14,
    category: 'Console',
    name: 'Steam Deck',
    rating: '4.8',
    reveiw: '(250 reviews)',
    price: '499$',
    image: consoleGaming6,
    description: 'Portable PC gaming on the go with Steam Deck’s power. Play your favorite titles anywhere with console-like controls.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaccff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaccff]',
    stockShadow: 'shadow-[0_0_10px_#aaccff]',
    bgBtn: 'bg-blue-500',
    borderColor: 'border-blue-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaccff,0_0_20px_#aaccff,0_0_40px_#aaccff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 15,
    category: 'Console',
    name: 'PlayStation 5 Digital Edition',
    rating: '4.7',
    reveiw: '(120 reviews)',
    price: '449$',
    image:consoleGaming7,
    description: 'All-digital PS5 with the same next-gen speed and graphics. Sleek, disc-free design for the modern gamer.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffbfff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffbfff]',
    stockShadow: 'shadow-[0_0_10px_#ffbfff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffbfff,0_0_20px_#ffbfff,0_0_40px_#ffbfff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 16,
    category: 'Console',
    name: 'Nintendo Switch Lite',
    rating: '4.5',
    reveiw: '(175 reviews)',
    price: '199$',
    image: consoleGaming8,
    description: 'Lightweight and portable, built for handheld gaming fun. Enjoy Nintendo’s best titles wherever you go.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd8a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd8a1]',
    stockShadow: 'shadow-[0_0_10px_#ffd8a1]',
    bgBtn: 'bg-yellow-500',
    borderColor: 'border-yellow-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffd8a1,0_0_20px_#ffd8a1,0_0_40px_#ffd8a1]',
    textColor: 'text-yellow-500',
    hoverText: 'group-hover:text-yellow-500',
  },
];
export const keyboardGaming = [
  {
    id: 17,
    category: 'Keyboard',
    name: 'Razer BlackWidow V4 Pro',
    rating: '4.9',
    reveiw: '(320 reviews)',
    price: '229$',
    image: keyboardGaming1,
    description:
      'Experience ultimate control with dedicated macro keys and a plush wrist rest. Designed for gamers who demand precision and speed.',
    shadow: 'hover:shadow-[0_0_10px_5px_#9ab0ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#9ab0ff]',
    stockShadow: 'shadow-[0_0_10px_#9ab0ff]',
    bgBtn: 'bg-blue-600',
    borderColor: 'border-blue-600',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#9ab0ff,0_0_20px_#9ab0ff,0_0_40px_#9ab0ff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 18,
    category: 'Keyboard',
    name: 'Corsair K100 RGB',
    rating: '4.8',
    reveiw: '(270 reviews)',
    price: '249$',
    image: keyboardGaming2,
    description:
      'The Corsair K100 delivers lightning-fast keystrokes with dynamic per-key RGB lighting. Built for performance and long-lasting durability.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffaa]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffaa]',
    stockShadow: 'shadow-[0_0_10px_#aaffaa]',
    bgBtn: 'bg-green-600',
    borderColor: 'border-green-600',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#aaffaa,0_0_20px_#aaffaa,0_0_40px_#aaffaa]',
    textColor: 'text-green-500',
    hoverText: 'group-hover:text-green-500',
  },
  {
    id: 19,
    category: 'Keyboard',
    name: 'SteelSeries Apex Pro TKL',
    rating: '4.9',
    reveiw: '(310 reviews)',
    price: '199$',
    image: keyboardGaming3,
    description:
      'Featuring adjustable actuation keys and an OLED display for customization. The Apex Pro redefines responsiveness and control.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffdfa3]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffdfa3]',
    stockShadow: 'shadow-[0_0_10px_#ffdfa3]',
    bgBtn: 'bg-orange-500',
    borderColor: 'border-orange-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffdfa3,0_0_20px_#ffdfa3,0_0_40px_#ffdfa3]',
    textColor: 'text-orange-500',
    hoverText: 'group-hover:text-orange-500',
  },
  {
    id: 20,
    category: 'Keyboard',
    name: 'Logitech G915 Lightspeed',
    rating: '4.7',
    reveiw: '(280 reviews)',
    price: '239$',
    image: keyboardGaming4,
    description:
      'A sleek, wireless mechanical keyboard with low-profile switches. Enjoy high-end performance without the clutter of cables.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffa1a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffa1a1]',
    stockShadow: 'shadow-[0_0_10px_#ffa1a1]',
    bgBtn: 'bg-red-500',
    borderColor: 'border-red-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffa1a1,0_0_20px_#ffa1a1,0_0_40px_#ffa1a1]',
    textColor: 'text-red-500',
    hoverText: 'group-hover:text-red-500',
  },
  {
    id: 21,
    category: 'Keyboard',
    name: 'HyperX Alloy Origins',
    rating: '4.6',
    reveiw: '(190 reviews)',
    price: '109$',
    image: keyboardGaming5,
    description:
      'Built with aircraft-grade aluminum for stability and strength. Custom mechanical switches ensure reliable and responsive typing.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffff]',
    stockShadow: 'shadow-[0_0_10px_#aaffff]',
    bgBtn: 'bg-teal-500',
    borderColor: 'border-teal-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#aaffff,0_0_20px_#aaffff,0_0_40px_#aaffff]',
    textColor: 'text-teal-500',
    hoverText: 'group-hover:text-teal-500',
  },
  {
    id: 22,
    category: 'Keyboard',
    name: 'Keychron K8 Pro',
    rating: '4.8',
    reveiw: '(220 reviews)',
    price: '129$',
    image: keyboardGaming6,
    description:
      'Wireless mechanical keyboard supporting both Mac and Windows. Compact, powerful, and perfect for productivity or play.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaccff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaccff]',
    stockShadow: 'shadow-[0_0_10px_#aaccff]',
    bgBtn: 'bg-blue-500',
    borderColor: 'border-blue-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#aaccff,0_0_20px_#aaccff,0_0_40px_#aaccff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 23,
    category: 'Keyboard',
    name: 'ASUS ROG Strix Scope RX',
    rating: '4.7',
    reveiw: '(160 reviews)',
    price: '139$',
    image: keyboardGaming7,
    description:
      'Equipped with ROG RX Optical switches for ultra-fast response. Designed for gamers who crave precision and RGB flair.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffbfff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffbfff]',
    stockShadow: 'shadow-[0_0_10px_#ffbfff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffbfff,0_0_20px_#ffbfff,0_0_40px_#ffbfff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 24,
    category: 'Keyboard',
    name: 'Ducky One 3 Mini',
    rating: '4.9',
    reveiw: '(200 reviews)',
    price: '119$',
    image: keyboardGaming8,
    description:
      'Compact 60% layout with vibrant color themes and hot-swappable switches. Perfect for minimal setups and fast gameplay.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd8a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd8a1]',
    stockShadow: 'shadow-[0_0_10px_#ffd8a1]',
    bgBtn: 'bg-yellow-500',
    borderColor: 'border-yellow-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffd8a1,0_0_20px_#ffd8a1,0_0_40px_#ffd8a1]',
    textColor: 'text-yellow-500',
    hoverText: 'group-hover:text-yellow-500',
  },
];

export const mouseGaming = [
  {
    id: 25,
    category: 'Mouse',
    name: 'Razer DeathAdder V3 Pro',
    rating: '4.9',
    reveiw: '(410 reviews)',
    price: '149$',
    image: mouseGaming1,
    description:
      'Engineered for speed and precision with an ultra-lightweight design. The DeathAdder V3 Pro is trusted by esports champions worldwide.',
    shadow: 'hover:shadow-[0_0_10px_5px_#9ab0ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#9ab0ff]',
    stockShadow: 'shadow-[0_0_10px_#9ab0ff]',
    bgBtn: 'bg-blue-600',
    borderColor: 'border-blue-600',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#9ab0ff,0_0_20px_#9ab0ff,0_0_40px_#9ab0ff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 26,
    category: 'Mouse',
    name: 'Logitech G Pro X Superlight',
    rating: '4.8',
    reveiw: '(350 reviews)',
    price: '159$',
    image: mouseGaming2,
    description:
      'One of the lightest wireless mice ever made, built for professional gamers. Experience effortless glide and pinpoint accuracy.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffaa]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffaa]',
    stockShadow: 'shadow-[0_0_10px_#aaffaa]',
    bgBtn: 'bg-green-600',
    borderColor: 'border-green-600',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#aaffaa,0_0_20px_#aaffaa,0_0_40px_#aaffaa]',
    textColor: 'text-green-500',
    hoverText: 'group-hover:text-green-500',
  },
  {
    id: 27,
    category: 'Mouse',
    name: 'Glorious Model O Wireless',
    rating: '4.7',
    reveiw: '(270 reviews)',
    price: '99$',
    image: mouseGaming3,
    description:
      'Honeycomb shell design keeps it ultralight and comfortable. Lag-free wireless connection for smooth, competitive gameplay.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffdfa3]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffdfa3]',
    stockShadow: 'shadow-[0_0_10px_#ffdfa3]',
    bgBtn: 'bg-orange-500',
    borderColor: 'border-orange-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffdfa3,0_0_20px_#ffdfa3,0_0_40px_#ffdfa3]',
    textColor: 'text-orange-500',
    hoverText: 'group-hover:text-orange-500',
  },
  {
    id: 28,
    category: 'Mouse',
    name: 'SteelSeries Aerox 9 Wireless',
    rating: '4.6',
    reveiw: '(220 reviews)',
    price: '139$',
    image: mouseGaming4,
    description:
      'Designed for MMO gamers with 12 programmable side buttons. Lightweight and durable, built for marathon gaming sessions.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffa1a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffa1a1]',
    stockShadow: 'shadow-[0_0_10px_#ffa1a1]',
    bgBtn: 'bg-red-500',
    borderColor: 'border-red-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffa1a1,0_0_20px_#ffa1a1,0_0_40px_#ffa1a1]',
    textColor: 'text-red-500',
    hoverText: 'group-hover:text-red-500',
  },
  {
    id: 29,
    category: 'Mouse',
    name: 'Corsair Dark Core RGB Pro',
    rating: '4.5',
    reveiw: '(180 reviews)',
    price: '119$',
    image: mouseGaming5,
    description:
      'Ergonomic wireless mouse with nine-zone dynamic RGB lighting. Delivers ultra-fast performance and comfortable long-hour use.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffff]',
    stockShadow: 'shadow-[0_0_10px_#aaffff]',
    bgBtn: 'bg-teal-500',
    borderColor: 'border-teal-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#aaffff,0_0_20px_#aaffff,0_0_40px_#aaffff]',
    textColor: 'text-teal-500',
    hoverText: 'group-hover:text-teal-500',
  },
  {
    id: 30,
    category: 'Mouse',
    name: 'ASUS ROG Gladius III',
    rating: '4.8',
    reveiw: '(260 reviews)',
    price: '129$',
    image: mouseGaming6,
    description:
      'ROG switches deliver ultra-precise clicks and extended lifespan. Customizable RGB lighting and detachable cable design.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaccff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaccff]',
    stockShadow: 'shadow-[0_0_10px_#aaccff]',
    bgBtn: 'bg-blue-500',
    borderColor: 'border-blue-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#aaccff,0_0_20px_#aaccff,0_0_40px_#aaccff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 31,
    category: 'Mouse',
    name: 'HyperX Pulsefire Haste',
    rating: '4.7',
    reveiw: '(240 reviews)',
    price: '79$',
    image: mouseGaming7,
    description:
      'Ultra-lightweight with a hex shell for faster movements. TTC Golden switches ensure crisp clicks and long-lasting durability.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffbfff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffbfff]',
    stockShadow: 'shadow-[0_0_10px_#ffbfff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffbfff,0_0_20px_#ffbfff,0_0_40px_#ffbfff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 32,
    category: 'Mouse',
    name: 'Cooler Master MM731',
    rating: '4.6',
    reveiw: '(200 reviews)',
    price: '89$',
    image: mouseGaming8,
    description:
      'Blends classic shape with cutting-edge wireless performance. Weighs under 60g, giving you total freedom in every game.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd8a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd8a1]',
    stockShadow: 'shadow-[0_0_10px_#ffd8a1]',
    bgBtn: 'bg-yellow-500',
    borderColor: 'border-yellow-500',
    textShadow:
      'group-hover:[text-shadow:0_0_10px_#ffd8a1,0_0_20px_#ffd8a1,0_0_40px_#ffd8a1]',
    textColor: 'text-yellow-500',
    hoverText: 'group-hover:text-yellow-500',
  },
];
export const headphoneGaming = [
  {
    id: 33,
    category: 'HeadPhone',
    name: 'Razer BlackShark V2 Pro',
    rating: '4.9',
    reveiw: '(420 reviews)',
    price: '179$',
    image: headphoneGaming1,
    description: 'High-performance wireless headset with ultra-clear mic. Perfect for immersive gaming and tournament play.',
    shadow: 'hover:shadow-[0_0_10px_5px_#9ab0ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#9ab0ff]',
    stockShadow: 'shadow-[0_0_10px_#9ab0ff]',
    bgBtn: 'bg-blue-600',
    borderColor: 'border-blue-600',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#9ab0ff,0_0_20px_#9ab0ff,0_0_40px_#9ab0ff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 34,
    category: 'HeadPhone',
    name: 'SteelSeries Arctis Nova Pro',
    rating: '4.8',
    reveiw: '(390 reviews)',
    price: '249$',
    image: headphoneGaming2,
    description: 'Premium sound quality with active noise cancellation. Designed for all-day comfort and clarity.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffaa]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffaa]',
    stockShadow: 'shadow-[0_0_10px_#aaffaa]',
    bgBtn: 'bg-green-600',
    borderColor: 'border-green-600',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffaa,0_0_20px_#aaffaa,0_0_40px_#aaffaa]',
    textColor: 'text-green-300',
    hoverText: 'group-hover:text-green-500',
  },
  {
    id: 35,
    category: 'HeadPhone',
    name: 'Corsair HS80 RGB Wireless',
    rating: '4.7',
    reveiw: '(260 reviews)',
    price: '149$',
    image: headphoneGaming3,
    description: 'Comfortable RGB headset with crystal-clear audio. Ideal for both PC and console gaming sessions.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffdfa3]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffdfa3]',
    stockShadow: 'shadow-[0_0_10px_#ffdfa3]',
    bgBtn: 'bg-orange-500',
    borderColor: 'border-orange-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffdfa3,0_0_20px_#ffdfa3,0_0_40px_#ffdfa3]',
    textColor: 'text-orange-500',
    hoverText: 'group-hover:text-orange-500',
  },
  {
    id: 36,
    category: 'HeadPhone',
    name: 'Logitech G Pro X 2 Lightspeed',
    rating: '4.8',
    reveiw: '(310 reviews)',
    price: '199$',
    image: headphoneGaming4,
    description: 'Pro-level wireless headset with surround sound. Built for esports and competitive gaming environments.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffa1a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffa1a1]',
    stockShadow: 'shadow-[0_0_10px_#ffa1a1]',
    bgBtn: 'bg-red-500',
    borderColor: 'border-red-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffa1a1,0_0_20px_#ffa1a1,0_0_40px_#ffa1a1]',
    textColor: 'text-red-300',
    hoverText: 'group-hover:text-red-500',
  },
  {
    id: 37,
    category: 'HeadPhone',
    name: 'HyperX Cloud Alpha Wireless',
    rating: '4.9',
    reveiw: '(340 reviews)',
    price: '199$',
    image: headphoneGaming5,
    description: 'Massive battery life and strong wireless performance. Tuned for deep bass and crisp sound details.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffff]',
    stockShadow: 'shadow-[0_0_10px_#aaffff]',
    bgBtn: 'bg-teal-500',
    borderColor: 'border-teal-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffff,0_0_20px_#aaffff,0_0_40px_#aaffff]',
    textColor: 'text-teal-500',
    hoverText: 'group-hover:text-teal-500',
  },
  {
    id: 38,
    category: 'HeadPhone',
    name: 'ASUS ROG Delta S Wireless',
    rating: '4.7',
    reveiw: '(210 reviews)',
    price: '169$',
    image: headphoneGaming6,
    description: 'Sleek, low-latency headset with dual connectivity. Optimized for clear communication and precision audio.',
    shadow: 'hover:shadow-[0_0_10px_5px_#aaccff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaccff]',
    stockShadow: 'shadow-[0_0_10px_#aaccff]',
    bgBtn: 'bg-blue-500',
    borderColor: 'border-blue-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaccff,0_0_20px_#aaccff,0_0_40px_#aaccff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 39,
    category: 'HeadPhone',
    name: 'Audeze Maxwell Wireless',
    rating: '4.8',
    reveiw: '(230 reviews)',
    price: '299$',
    image: headphoneGaming7,
    description: 'Audiophile-grade planar magnetic headset. Delivers unmatched clarity, bass, and wireless freedom.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffbfff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffbfff]',
    stockShadow: 'shadow-[0_0_10px_#ffbfff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffbfff,0_0_20px_#ffbfff,0_0_40px_#ffbfff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 40,
    category: 'HeadPhone',
    name: 'EPOS H6PRO Closed',
    rating: '4.6',
    reveiw: '(150 reviews)',
    price: '179$',
    image: headphoneGaming8,
    description: 'Closed-back design for noise isolation and focus. Engineered for comfort and accurate game sound.',
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd8a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd8a1]',
    stockShadow: 'shadow-[0_0_10px_#ffd8a1]',
    bgBtn: 'bg-yellow-500',
    borderColor: 'border-yellow-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffd8a1,0_0_20px_#ffd8a1,0_0_40px_#ffd8a1]',
    textColor: 'text-yellow-500',
    hoverText: 'group-hover:text-yellow-500',
  },
];
export const monitorGaming = [
  {
    id: 41,
    category: 'Monitor',
    name: 'ASUS ROG Swift PG27AQN',
    rating: '4.9',
    reveiw: '(520 reviews)',
    price: '899$',
    description: '27-inch gaming monitor with 4K UHD resolution.Ultra-fast 165Hz refresh rate for smooth gameplay.',
    image: MinitorsGaming1,
    shadow: 'hover:shadow-[0_0_10px_5px_#9ab0ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#9ab0ff]',
    stockShadow: 'shadow-[0_0_10px_#9ab0ff]',
    bgBtn: 'bg-blue-600',
    borderColor: 'border-blue-600',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#9ab0ff,0_0_20px_#9ab0ff,0_0_40px_#9ab0ff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 42,
    category: 'Monitor',
    name: 'Alienware AW3423DWF QD-OLED',
    rating: '4.8',
    reveiw: '(460 reviews)',
    price: '1099$',
    description: '34-inch curved QD-OLED monitor with immersive colors.\nDesigned for ultra-smooth and responsive gaming.',
    image: MinitorsGaming2,
    shadow: 'hover:shadow-[0_0_10px_5px_#ffb6ff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffb6ff]',
    stockShadow: 'shadow-[0_0_10px_#ffb6ff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffb6ff,0_0_20px_#ffb6ff,0_0_40px_#ffb6ff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 43,
    category: 'Monitor',
    name: 'Samsung Odyssey G9 Neo',
    rating: '4.9',
    reveiw: '(610 reviews)',
    price: '1499$',
    description: '49-inch ultra-wide curved gaming monitor.\nQD-OLED technology for stunning visuals and deep blacks.',
    image:MinitorsGaming3,
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffff]',
    stockShadow: 'shadow-[0_0_10px_#aaffff]',
    bgBtn: 'bg-teal-500',
    borderColor: 'border-teal-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffff,0_0_20px_#aaffff,0_0_40px_#aaffff]',
    textColor: 'text-teal-500',
    hoverText: 'group-hover:text-teal-500',
  },
  {
    id: 44,
    category: 'Monitor',
    name: 'Gigabyte M27Q X QHD 240Hz',
    rating: '4.7',
    reveiw: '(330 reviews)',
    price: '429$',
    description: '27-inch QHD monitor with 240Hz refresh rate.\nIdeal for competitive gaming with minimal input lag.',
    image: MinitorsGaming4,
    shadow: 'hover:shadow-[0_0_10px_5px_#aaffaa]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaffaa]',
    stockShadow: 'shadow-[0_0_10px_#aaffaa]',
    bgBtn: 'bg-green-600',
    borderColor: 'border-green-600',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaffaa,0_0_20px_#aaffaa,0_0_40px_#aaffaa]',
    textColor: 'text-green-500',
    hoverText: 'group-hover:text-green-500',
  },
  {
    id: 45,
    category: 'Monitor',
    name: 'LG UltraGear 27GR95QE OLED',
    rating: '4.8',
    reveiw: '(410 reviews)',
    price: '999$',
    description: '27-inch OLED monitor with 1ms response time.\nPerfect for fast-paced FPS and immersive gaming experiences.',
    image: MinitorsGaming5,
    shadow: 'hover:shadow-[0_0_10px_5px_#ffdfa3]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffdfa3]',
    stockShadow: 'shadow-[0_0_10px_#ffdfa3]',
    bgBtn: 'bg-orange-500',
    borderColor: 'border-orange-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffdfa3,0_0_20px_#ffdfa3,0_0_40px_#ffdfa3]',
    textColor: 'text-orange-500',
    hoverText: 'group-hover:text-orange-500',
  },
  {
    id: 46,
    category: 'Monitor',
    name: 'MSI MEG 342C QD-OLED',
    rating: '4.7',
    reveiw: '(280 reviews)',
    price: '1199$',
    description: '34-inch curved QD-OLED display.\nOffers vibrant colors and smooth gaming performance.',
    image: MinitorsGaming6,
    shadow: 'hover:shadow-[0_0_10px_5px_#aaccff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#aaccff]',
    stockShadow: 'shadow-[0_0_10px_#aaccff]',
    bgBtn: 'bg-blue-500',
    borderColor: 'border-blue-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#aaccff,0_0_20px_#aaccff,0_0_40px_#aaccff]',
    textColor: 'text-blue-500',
    hoverText: 'group-hover:text-blue-500',
  },
  {
    id: 47,
    category: 'Monitor',
    name: 'BenQ MOBIUZ EX3210U 4K',
    rating: '4.6',
    reveiw: '(270 reviews)',
    price: '899$',
    description: '32-inch 4K gaming monitor with HDR support.\nSharp visuals and accurate colors for immersive gameplay.',
    image: MinitorsGaming7,
    shadow: 'hover:shadow-[0_0_10px_5px_#ffbfff]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffbfff]',
    stockShadow: 'shadow-[0_0_10px_#ffbfff]',
    bgBtn: 'bg-pink-500',
    borderColor: 'border-pink-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffbfff,0_0_20px_#ffbfff,0_0_40px_#ffbfff]',
    textColor: 'text-pink-500',
    hoverText: 'group-hover:text-pink-500',
  },
  {
    id: 48,
    category: 'Monitor',
    name: 'AOC AGON PRO AG274QZM',
    rating: '4.7',
    reveiw: '(240 reviews)',
    price: '749$',
    description: '27-inch QHD monitor with high refresh rate.\nDesigned for competitive gamers seeking smooth visuals.',
    image: MinitorsGaming8,
    shadow: 'hover:shadow-[0_0_10px_5px_#ffd8a1]',
    btnShadow: 'group-hover:shadow-[0_0_10px_5px_#ffd8a1]',
    stockShadow: 'shadow-[0_0_10px_#ffd8a1]',
    bgBtn: 'bg-yellow-500',
    borderColor: 'border-yellow-500',
    textShadow: 'group-hover:[text-shadow:0_0_10px_#ffd8a1,0_0_20px_#ffd8a1,0_0_40px_#ffd8a1]',
    textColor: 'text-yellow-500',
    hoverText: 'group-hover:text-yellow-500',
  },
]
export const AllProductsList = [
  ...computerGaming,
  ...consoleGaming,
  ...keyboardGaming,
  ...mouseGaming,
  ...headphoneGaming,
  ...monitorGaming
];
